### ISSUE TITLE
Query data using mouse click (with metadata from shp)

### ISSUE THREAD

**Issue by midraed** [FAO-GSP/GSOCmap-web-services#1]
Query data using the mouse. The output should include the value of the current GSOCmap plus the value of some fields in a shapefile.
Result has to be shown in a [popup](http://openlayers.org/en/latest/examples/popup.html) window.

**Comment by mauriciopasquier** [comment]
Popup and SOC value querying implemented.

**Comment by mauriciopasquier** [comment]
What metadata should I use for the popup?

**Comment by midraed** [comment]
We will skip the metadata. Just the value of the GSOCmap as it is right now.
