### ISSUE TITLE
Configure tile caching

### ISSUE THREAD

**Issue by mauriciopasquier** [FAO-GSP/GSOCmap-web-services#10]
For reference, I created a gridset with tile size based on GSOCmap layer (recommended 512 x 512) so it can use the cache. When trying to add this gridset to defaults, I get this error:

> Loading quota store failed, the disk quota subsystem is disabled, please re-configure: Could not open  JDBC Connection for transaction; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-119])"

**Comment by midraed** [comment]
solved

**Comment by mauriciopasquier** [comment]
Cache it's working but the tiles are not served from it.

Besides, at seeding we hit this bug: https://gis.stackexchange.com/a/264544

**Comment by mauriciopasquier** [comment]
Another bug: it seems geowebcache can't read correctly a layer name with dots. [This link to 1.2.0](http://54.229.242.119/geoserver/gwc/rest/seed/GSOC:GSOCmapV1.2.0) is reported as "Unknown layer GSOC:GSOCmapV1.2"

**Comment by mauriciopasquier** [comment]
Done! I had to:
- ask for cache explicitely in openlayers
- configure geowebcache storage (it now resides in `data_dir/cache_dir`)
- configure each layer with max-age in seconds to keep in a browser cache, for example. This is in Layer -> Publishing -> HTTP Settings. In nginx I set `Cache-Control: public, no transform` for every other asset with expiration of 1 day (we can use more but we should discuss it)
- rename the layers without dots (a bug in geowebcache prevents seeding them)
- seed the cache with our layers:

```sh
curl -u "user:password" -H "Content-type: text/xml" -H "Accept: text/xml" -XPOST -i -d "<seedRequest> <name>GSOC:NE2</name> <type>seed</type> <gridSetId>EPSG:4326</gridSetId> <bounds> <coords> <double>-180</double> <double>-90</double> <double>180</double> <double>90</double> </coords> </bounds> <zoomStart>0</zoomStart> <zoomStop>10</zoomStop> <format>image/jpeg</format> <threadCount>02</threadCount> </seedRequest>" "http://localhost:8080/geoserver/gwc/rest/seed/GSOC:NE2.xml"

curl -u "user:password" -H "Content-type: text/xml" -H "Accept: text/xml" -XPOST -i -d "<seedRequest> <name>GSOC:GSOCmapV120</name> <type>seed</type> <gridSetId>EPSG:4326</gridSetId> <bounds> <coords> <double>-180</double> <double>-90</double> <double>180</double> <double>90</double> </coords> </bounds> <zoomStart>0</zoomStart> <zoomStop>10</zoomStop> <format>image/png8</format> <threadCount>02</threadCount> </seedRequest>" "http://localhost:8080/geoserver/gwc/rest/seed/GSOC:GSOCmapV120.xml"
```
