### ISSUE TITLE
Increase memory for geoserver

### ISSUE THREAD

**Issue by midraed** [FAO-GSP/GSOCmap-web-services#11]
current memory is 2 Gb, should be 4

**Comment by mauriciopasquier** [comment]
Done, configured in the geoserver startup script (`bin/startup.sh`):

```sh
JAVA_OPTS="-Xms4G -Xmx4G -XX:+UseParallelGC -XX:SoftRefLRUPolicyMSPerMB=36000"
```

Also configured more optimization options, following these resources:

- http://docs.geoserver.org/stable/en/user/production/config.html
- http://docs.geoserver.org/stable/en/user/production/container.html
- http://geoserver.geo-solutions.it/edu/en/adv_gsconfig/gsproduction.html
- https://stackoverflow.com/questions/2101518/difference-between-xxuseparallelgc-and-xxuseparnewgc#2141858
