### ISSUE TITLE
Statistics tool

### ISSUE THREAD

**Issue by midraed** [FAO-GSP/GSOCmap-web-services#12]
Statistics tool

Text should be:
**Zonal SOC Stock Statistics Tool**

Use Crtl+Drag to draw an extent and calculate statistics for it. Crtl+Drag on the corners or edges of the extent to resize it.

(ONLY when there is an extent):
**Total Stock**: 3438591.9 Mg    (use sum)

**SOC density**
Min: 50.91 Mg ha-1
Max: 259.13 Mg ha-1
Mean: 159.35 Mg ha-1 (use avg)
Stddev: 35.35 Mg ha-1

**Comment by mauriciopasquier** [comment]
Everything rounded to 2 decimals?

**Comment by midraed** [comment]
Total Stock can have one decimal. The SOC density must be rounded to  2.
