### ISSUE TITLE
Download Links

### ISSUE THREAD

**Issue by yigini** [FAO-GSP/GSOCmap-web-services#16]
Download stops at random times.
http://54.229.242.119/GSOCmap/downloads/GSOCmapV1.1.0.tif
http://54.229.242.119/GSOCmap/downloads/GSOCmapV1.2.0.tif
@mauriciopasquier @midraed

**Comment by mauriciopasquier** [comment]
I'll have to configure a web server, like nginx, optimized for large files, and proxy requests to geoserver through that instead.

**Comment by mauriciopasquier** [comment]
Done!
