### ISSUE TITLE
Dynamic contributors information for the current spatial extent. 

### ISSUE THREAD

**Issue by midraed** [FAO-GSP/GSOCmap-web-services#2]
Get the data holder for the current extent and show them on the screen.
 The list of contributors (data holders) should be printed at the bottom of the map (like in google earth).

**Comment by midraed** [comment]
We want to display the list institutions who contributed to the GSOC map in the bottom bar.  The information should be the column `metadata_full_institution` from layer `GSOC:metadata` for the current spatial extent

**Comment by mauriciopasquier** [comment]
Until we discuss the right formatting, we are showing a list of ISOs for the current view, if there are less than 10, otherwise a generic message with the total contributors.
