### ISSUE TITLE
Adding a pop-up window when a user open the website for the first time.

### ISSUE THREAD

**Issue by midraed** [FAO-GSP/GSOCmap-web-services#3]
The popup window should include Project information, technical report, link to contributors, contact point, how to contribute.
@yigini / @midraed will decide on the contents
@mauriciopasquier will work on the implementation

**Comment by midraed** [comment]
Content:
**This interactive map allows you to explore the GSOCmap.**

This map provides users with very useful information to monitor the soil condition, identify degraded areas, set restoration targets, explore SOC sequestration potentials, support the greenhouse gas emission reporting under the UNFCCC and make evidence based decisions to mitigate and adapt to a changing climate.

[Home](http://www.fao.org/global-soil-partnership/pillars-action/4-information-and-data/global-soil-organic-carbon-gsoc-map/en/)
[Leaflet](http://www.fao.org/documents/card/en/c/fb798a4c-ff06-4468-ad18-27787d1f3456/)
[Contributors](http://www.fao.org/global-soil-partnership/pillars-action/4-information-and-data/global-soil-organic-carbon-gsoc-map/gsocmap-contributors/en/)
Technical report (coming soon)

(c) FAO, 2018

**Comment by mauriciopasquier** [comment]
Implementation ready. Right now it remembers the user preference for popup sites for 30 days, and then it appears again. We can change that to any value or infinite but I though it was nice for news or stuff like that.

**Comment by mauriciopasquier** [comment]
We decided to leave out the option for not seeing the modal anymore, now it's mandatory but easily dismissable.

Further development on this should go on separate issues.
