### ISSUE TITLE
Full GSOCmap download

### ISSUE THREAD

**Issue by midraed** [FAO-GSP/GSOCmap-web-services#5]
Provide a link to allow users to download the GSOCmap.

**Comment by mauriciopasquier** [comment]
We're talking about the giant .tif file, right?

**Comment by midraed** [comment]
yeah

**Comment by mauriciopasquier** [comment]
We should find out if FAO already has a file server we can use, so we outsource this task, bandwith and server resources.

**Comment by midraed** [comment]
We agreed on providing a direct link from our server. We have to add a new "download tool" in the toolbar.
icon: data-transfer-download
order: info - crop - stats - download

Text:
**Download GSOCmap raster tiff file**

Can we embed jetty directory listing here?

**Comment by mauriciopasquier** [comment]
I think embedding the listing in the sidebar will look awful, but I can get the list and show it formatted or we can simply link to the directory listing.

In my opinion the latter is not that ugly, it's common practice and it's the simplest solution.

**Comment by midraed** [comment]
I agree with your suggestion. Let's get the list and show it there formatted. What do you think @yigini ?
