### ISSUE TITLE
Load shapefile in db

### ISSUE THREAD

**Issue by mauriciopasquier** [FAO-GSP/GSOCmap-web-services#6]
For #1, we need to query fields in a shapefile. Currently it is loaded directly in the geoserver but to update it easily it should reside in our postgresql, and from there somehow update the metadata layer.

**Comment by midraed** [comment]
Addeed a new store to geoserver with the connection to postgis. Uploaded metadata layer as `GSOC:metadata`. 

Future updates of metadata should be done there only
