### ISSUE TITLE
fix bounding box for bottombar and replace text

### ISSUE THREAD

**Issue by midraed** [FAO-GSP/GSOCmap-web-services#9]
Content for bottom bar should come from `metadata_full_institution`. The maximum number of institutions could be 4. 

There is a problem with the bounding box, perhaps relate to order of parameters.

**Comment by mauriciopasquier** [comment]
The WFS specification assumes no coordinate system, so I had to specify EPSG:4326.

**Comment by mauriciopasquier** [comment]
We'll use `metadata_full_institution (iso)` for contributors.

**Comment by midraed** [comment]
The problem with the bounding box was caused by the parameter `Loose bbox` in PostGIS geoserver store. After disabling that parameter, the bounding box for the layer is okay.
